/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package login;

import com.itextpdf.text.Document;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import com.itextpdf.text.pdf.PdfPTable;

import java.io.FileOutputStream;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;



/**
 *
 * @author LENOVO
 */
public class Pembayaran extends javax.swing.JFrame {

    private int selectedRow;


    /**
     * Creates new form Pembayaran
     */
    public Pembayaran() {
        initComponents();
        loadOrderData();
        setTanggalOtomatis();

    }
    private JTextField txtTotalHarga; // Deklarasi variabel untuk JTextField yang digunakan untuk menampilkan total harga makanan
    private JTextField txtBayar; // Deklarasi variabel untuk JTextField yang digunakan untuk menampilkan jumlah yang dibayar oleh pengguna
    private void setTanggalOtomatis() {
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String tanggalSekarang = sdf.format(new Date());  // Format tanggal saat ini
        tanggal.setText(tanggalSekarang);  // Menetapkan tanggal otomatis ke JTextField
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Jpanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        Tanggal = new javax.swing.JLabel();
        Pembayaran = new javax.swing.JLabel();
        tanggal = new javax.swing.JTextField();
        pembayaran = new javax.swing.JComboBox<>();
        TotalHarga = new javax.swing.JLabel();
        totalHargaField = new javax.swing.JTextField();
        Bayar = new javax.swing.JLabel();
        bayar = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Bayar1 = new javax.swing.JLabel();
        txtkembalian = new javax.swing.JTextField();
        CetakTransaksiBT1 = new javax.swing.JButton();
        namaTextField = new javax.swing.JTextField();
        Tanggal1 = new javax.swing.JLabel();
        exit = new javax.swing.JButton();
        CetakTransaksiBT3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Jpanel1.setBackground(new java.awt.Color(255, 255, 255));
        Jpanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        Jpanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        Tanggal.setText("Tanggal");
        Jpanel1.add(Tanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, 20));

        Pembayaran.setText("Pembayaran");
        Jpanel1.add(Pembayaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, -1, 20));

        tanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanggalActionPerformed(evt);
            }
        });
        Jpanel1.add(tanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 150, -1));

        pembayaran.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash" }));
        pembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pembayaranActionPerformed(evt);
            }
        });
        Jpanel1.add(pembayaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 150, 30));

        TotalHarga.setText("Total Harga");
        TotalHarga.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                TotalHargaAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        Jpanel1.add(TotalHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, -1, 20));

        totalHargaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalHargaFieldActionPerformed(evt);
            }
        });
        Jpanel1.add(totalHargaField, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 128, 160, -1));

        Bayar.setText("Bayar");
        Bayar.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                BayarAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        Jpanel1.add(Bayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 156, -1, 30));

        bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bayarActionPerformed(evt);
            }
        });
        Jpanel1.add(bayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, 160, -1));

        jPanel2.setBackground(new java.awt.Color(255, 75, 58));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Pembayaran");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Jpanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1160, 90));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id Pesanan", "Nama Makanan", "Jumlah", "Harga"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        Jpanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 120, 490, 430));

        Bayar1.setText("Kembalian");
        Bayar1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                Bayar1AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        Jpanel1.add(Bayar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, -1, 30));

        txtkembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkembalianActionPerformed(evt);
            }
        });
        Jpanel1.add(txtkembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 192, 160, 30));

        CetakTransaksiBT1.setBackground(new java.awt.Color(242, 242, 242));
        CetakTransaksiBT1.setText("Cetak Transaksi");
        CetakTransaksiBT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CetakTransaksiBT1ActionPerformed(evt);
            }
        });
        Jpanel1.add(CetakTransaksiBT1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 250, 120, -1));

        namaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaTextFieldActionPerformed(evt);
            }
        });
        Jpanel1.add(namaTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 150, -1));

        Tanggal1.setText("Nama");
        Jpanel1.add(Tanggal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, -1));

        exit.setBackground(new java.awt.Color(255, 75, 58));
        exit.setForeground(new java.awt.Color(255, 255, 255));
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        Jpanel1.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 80, -1));

        CetakTransaksiBT3.setBackground(new java.awt.Color(255, 75, 58));
        CetakTransaksiBT3.setForeground(new java.awt.Color(255, 255, 255));
        CetakTransaksiBT3.setText("Kembalian");
        CetakTransaksiBT3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CetakTransaksiBT3ActionPerformed(evt);
            }
        });
        Jpanel1.add(CetakTransaksiBT3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Jpanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Jpanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pembayaranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pembayaranActionPerformed

    private void totalHargaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalHargaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalHargaFieldActionPerformed

    private void bayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bayarActionPerformed

    private void TotalHargaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_TotalHargaAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_TotalHargaAncestorAdded

    private void BayarAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_BayarAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_BayarAncestorAdded

    private void Bayar1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_Bayar1AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_Bayar1AncestorAdded

    private void txtkembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkembalianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkembalianActionPerformed

    private void CetakTransaksiBT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CetakTransaksiBT1ActionPerformed
         
       try {
        // Ambil nilai total harga dan uang yang dibayar
        double totalHarga = Double.parseDouble(totalHargaField.getText()); // Ambil total harga dari text field
        double uangDibayar = Double.parseDouble(bayar.getText()); // Ambil uang yang dibayar dari text field

        // Hitung kembalian
        double kembalian = uangDibayar - totalHarga;

        // Periksa apakah uang yang dibayar cukup
        if (kembalian < 0) {
            JOptionPane.showMessageDialog(this, "Uang yang dibayar tidak cukup!", "Error", JOptionPane.ERROR_MESSAGE);
            return; // Hentikan proses jika uang tidak cukup
        } else {
            // Tampilkan hasil kembalian di text field Kembalian
            txtkembalian.setText(String.format("%.2f", kembalian)); // Format angka 2 decimal
        }
        
        // Membuat dokumen PDF
        Document document = new Document();
        
        // Tentukan path untuk menyimpan PDF di folder Dokumen pada C:
        String path = System.getProperty("user.home") + "\\Documents\\Transaksi.pdf"; 
        PdfWriter.getInstance(document, new FileOutputStream(path));

        // Buka dokumen
        document.open();

        // Tambahkan header ke PDF
        document.add(new Paragraph("Detail Transaksi"));
        document.add(new Paragraph("Tanggal: " + tanggal.getText())); // Tanggal transaksi
        document.add(new Paragraph("Nama: " + namaTextField.getText())); // Nama pengguna dari TextField
        document.add(new Paragraph(" ")); // Baris kosong

        // Membuat tabel PDF
        PdfPTable table = new PdfPTable(jTable1.getColumnCount());
        for (int i = 0; i < jTable1.getColumnCount(); i++) {
            table.addCell(jTable1.getColumnName(i)); // Menambahkan nama kolom ke tabel PDF
        }

        // Mengisi data dari JTable ke tabel PDF
        for (int row = 0; row < jTable1.getRowCount(); row++) {
            for (int col = 0; col < jTable1.getColumnCount(); col++) {
                table.addCell(jTable1.getValueAt(row, col).toString()); // Menambahkan data dari setiap cell JTable
            }
        }

        // Tambahkan tabel ke PDF
        document.add(table);

        // Tambahkan total harga dan kembalian
        document.add(new Paragraph(" "));
        document.add(new Paragraph("Total Harga: " + totalHargaField.getText()));
        document.add(new Paragraph("Uang Dibayar: " + bayar.getText()));
        document.add(new Paragraph("Kembalian: " + txtkembalian.getText()));

        // Tutup dokumen
        document.close();

        // Simpan data ke database
        PesananDao dao = new PesananDao();
        dao.simpanPesanan(namaTextField.getText(), Double.parseDouble(totalHargaField.getText()), "Cash", tanggal.getText());

        // Tampilkan pesan sukses
        JOptionPane.showMessageDialog(this, "PDF berhasil dicetak dan transaksi disimpan ke database!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Gagal mencetak PDF!", "Kesalahan", JOptionPane.ERROR_MESSAGE);
    }


    }//GEN-LAST:event_CetakTransaksiBT1ActionPerformed

    private void tanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanggalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tanggalActionPerformed

    private void namaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaTextFieldActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void CetakTransaksiBT3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CetakTransaksiBT3ActionPerformed
        // TODO add your handling code here:
        try {
        // Ambil nilai total harga dan uang yang dibayar
        double totalHarga = Double.parseDouble(totalHargaField.getText()); // Ambil total harga dari text field
        double uangDibayar = Double.parseDouble(bayar.getText()); // Ambil uang yang dibayar dari text field

        // Hitung kembalian
        double kembalian = uangDibayar - totalHarga;

        // Periksa apakah uang yang dibayar cukup
        if (kembalian < 0) {
            JOptionPane.showMessageDialog(this, "Uang yang dibayar tidak cukup!", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            // Tampilkan hasil kembalian di text field Kembalian
            txtkembalian.setText(String.format("%.2f", kembalian)); // Format angka 2 decimal
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Masukkan nilai yang valid untuk Total Harga dan Bayar!", "Input Error", JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_CetakTransaksiBT3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pembayaran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bayar;
    private javax.swing.JLabel Bayar1;
    private javax.swing.JButton CetakTransaksiBT1;
    private javax.swing.JButton CetakTransaksiBT3;
    private javax.swing.JPanel Jpanel1;
    private javax.swing.JLabel Pembayaran;
    private javax.swing.JLabel Tanggal;
    private javax.swing.JLabel Tanggal1;
    private javax.swing.JLabel TotalHarga;
    private javax.swing.JTextField bayar;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField namaTextField;
    private javax.swing.JComboBox<String> pembayaran;
    private javax.swing.JTextField tanggal;
    private javax.swing.JTextField totalHargaField;
    private javax.swing.JTextField txtkembalian;
    // End of variables declaration//GEN-END:variables

    private void loadOrderData() {
    // Kolom untuk tabel
    String[] columnNames = {"Nama Menu", "Jumlah", "Harga", "Tanggal", "Metode Pembayaran"};
    DefaultTableModel tableModel = new DefaultTableModel(columnNames, 0);

    // Ambil data terbaru dari OrderRepository
    OrderRepository repository = new OrderRepository();
    // Mengambil data pesanan terbaru dari repository yang berupa array
    List<Object[]> latestOrder = repository.getLatestOrderDetails();

    double totalHarga = 0; // Variabel untuk menghitung total harga

    // Tambahkan data terbaru ke model tabel dan hitung total harga
    for (Object[] order : latestOrder) {
        // Menambahkan setiap baris data pesanan ke dalam model tabel
        tableModel.addRow(order);
        totalHarga += (double) order[2]; // Harga ada di indeks ke-2
    }

    // Set model ke jTable1
    jTable1.setModel(tableModel);

    // Tampilkan total harga di text field
    totalHargaField.setText(String.valueOf(totalHarga));
}

}